### ISSUE TITLE
Android build

### ISSUE THREAD

**Issue by dappledore** [freshplanet/ANE-Chartboost#18]
Im building just for Android on Windows 8, i set the build config with relevant paths for flex and Android SDK, i also  setup the JAVA_HOME variable. But i get errors below when compiling , any ideas? Cant seem to find Android, even though i setup the SDK path? cheers

```
    [javac] Compiling 7 source files to Flash\ANE-Chartboost\andr
oid\temp\classes
    [javac] ANE-Chartboost\android\src\com\freshplanet\ane\
AirChartboost\AirChartboostExtension.java:21: package android.util does not exist
    [javac] import android.util.Log;
    [javac]                    ^
    [javac] ANE-Chartboost\android\src\com\freshplanet\ane\
AirChartboost\AirChartboostExtension.java:23: package com.adobe.fre does not exist
    [javac] import com.adobe.fre.FREContext;
    [javac]                     ^
    [javac] Flash\ANE-Chartboost\android\src\com\freshplanet\ane\
AirChartboost\AirChartboostExtension.java:24: package com.adobe.fre does not exist
```

**Comment by dappledore** [comment]
I solved by escaping the backslashes for the path in build.config also need to specify .exe for windows in the bin.ext and specify JVM path in jvm.config in flexSDK bin folder like (needs to  be 32bit)
java.home=C:/Program Files (x86)/Java/jre7

**Comment by kerrgrant** [comment]
Hi,

I'm currently having a similar issue on Mac. I'm just getting to grips with ANE development by simply trying to recompile the .ANE file for the AlertNativeExtension. I have $PATH entries for the AIR SDK, Java SDK and Ant. The contents of my build.config file is the following:

```
name = AirAlert

flex.sdk = ~/Desktop/AIRSDK_Compiler

bin.ext = 

ios.sdkversion = iphoneos

android.sdk = ~/Library/Android/sdk
```

When I run ant the output states 'error: package com.adobe.fre does not exist' leading me to believe that it's simply a classpath issue.

Any ideas where I could be going wrong?

Cheers.
